name: AI Benchmark Tournament Run

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false


# Daily job to run all bots
jobs:
  bot_gpt4o:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'gpt-4o'
      llm_path: 'openai/gpt-4o'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_GPT4O }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o1:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'o1'
      llm_path: 'openai/o1'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_GPT_O1 }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o1_preview:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'o1-preview'
      llm_path: 'openai/o1-preview'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_GPT_O1_PREVIEW }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_claude_sonnet_0620:
    needs: [bot_gpt4o]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'claude-3-5-sonnet-20240620'
      llm_path: 'anthropic/claude-3-5-sonnet-20240620'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_SONNET_0620 }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_claude_sonnet_1022:
    needs: [bot_gpt4o]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'claude-3-5-sonnet-20241022'
      llm_path: 'anthropic/claude-3-5-sonnet-20241022'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_SONNET_1022 }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_gemini:
    needs: [bot_gpt4o]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'gemini-exp-1206'
      llm_path: 'gemini/gemini-exp-1206'
      concurrency: 1
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_EXP_1206 }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_grok:
    needs: [bot_claude_sonnet_1022]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'grok-2-1212'
      llm_path: 'xai/grok-2-1212'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_GROK_2_1212 }}
      XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_llama:
    needs: [bot_claude_sonnet_1022]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'meta-llama-3.1-405b'
      llm_path: 'together_ai/meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_LLAMA_3_1 }}
      TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_deepseek:
    needs: [bot_claude_sonnet_1022]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'deepseek-r1'
      llm_path: 'together_ai/deepseek-ai/DeepSeek-R1'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1 }}
      TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}
      ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_exa:
    needs: [bot_claude_sonnet_1022]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'exa'
      llm_path: 'openai/o1'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_EXA_BOT }}
      EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  bot_perplexity:
    needs: [bot_claude_sonnet_1022]
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'perplexity'
      llm_path: 'openai/o1'
    secrets:
      METACULUS_TOKEN: ${{ secrets.METAC_PERPLEXITY_BOT }}
      PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

