name: AI Benchmark Tournament Build/Run

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false


# Daily job to run all bots
jobs:
  bot_gpt4o:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'gpt-4o'
      llm_path: 'openai/gpt-4o'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT4O }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o1:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'o1'
      llm_path: 'openai/o1'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_O1 }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_o1_preview:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'o1-preview'
      llm_path: 'openai/o1-preview'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GPT_O1_PREVIEW }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_claude_sonnet_0620:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'claude-3-5-sonnet-20240620'
      llm_path: 'anthropic/claude-3-5-sonnet-20240620'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_SONNET_0620 }}
      INPUT_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_claude_sonnet_1022:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'claude-3-5-sonnet-20241022'
      llm_path: 'anthropic/claude-3-5-sonnet-20241022'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_SONNET_1022 }}
      INPUT_ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_gemini:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'gemini-exp-1206'
      llm_path: 'gemini/gemini-exp-1206'
      concurrency: 1
      call_very_slowly: "True"
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GEMINI_EXP_1206 }}
      INPUT_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_grok:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'grok-2-1212'
      llm_path: 'xai/grok-2-1212'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_GROK_2_1212 }}
      INPUT_XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_llama:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'meta-llama-3.1-405b'
      llm_path: 'openrouter/meta-llama/llama-3.1-405b-instruct'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_LLAMA_3_1 }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_deepseek:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'deepseek-r1'
      llm_path: 'openrouter/deepseek/deepseek-r1'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_DEEPSEEK_R1 }}
      INPUT_OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
      INPUT_ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
      INPUT_ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}

  bot_exa:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'exa'
      llm_path: 'openai/o1'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_EXA_BOT }}
      INPUT_EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

  bot_perplexity:
    uses: ./.github/workflows/bot-template.yaml
    with:
      bot_name: 'perplexity'
      llm_path: 'openai/o1'
    secrets:
      INPUT_METACULUS_TOKEN: ${{ secrets.METAC_PERPLEXITY_BOT }}
      INPUT_PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
      INPUT_OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

