on:
  workflow_call:
    inputs:
      bot_name:
        required: true
        type: string
      llm_path:
        required: true
        type: string
      concurrency:
        required: false
        type: number
        default: 5
      skip_previous:
        required: false
        type: string
        default: "True"
      tournament_id:
        required: false
        type: number
        default: 1
    secrets:
      METACULUS_TOKEN:
        required: true
      OPENAI_API_KEY:
        required: false
      ANTHROPIC_API_KEY:
        required: false
      GEMINI_API_KEY:
        required: false
      XAI_API_KEY:
        required: false
      TOGETHERAI_API_KEY:
        required: false
      EXA_API_KEY:
        required: false
      PERPLEXITY_API_KEY:
        required: false
      ASKNEWS_CLIENT_ID:
        required: false
      ASKNEWS_SECRET:
        required: false

jobs:
  run_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Run bot
        run: |
          poetry run python main.py --llm ${{ inputs.llm_path }} --concurrency ${{ inputs.concurrency }} --skip_previous ${{ inputs.skip_previous }} --tournament_id ${{ inputs.tournament_id }}
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}
          EXA_API_KEY: ${{ secrets.EXA_API_KEY }}
          PERPLEXITY_API_KEY: ${{ secrets.PERPLEXITY_API_KEY }}
