name: Daily Build

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

# Daily job to run all bots
jobs:
  daily_build:
    runs-on: ubuntu-latest
    steps:
      # setup repository with all necessary dependencies
      - name: Check out repository
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      # NOTE: Q3-Q4 had bots 1-5, bots 6-12 started in Q1 but have some model overlap
      # run bot B6
      - name: Run with GPT-4o
        run: |
          poetry run python main.py --llm openai/gpt-4o
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B6 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # run bot B7
      - name: Run with o1-preview
        run: |
          poetry run python main.py --llm openai/o1-preview
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B7 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # run bot B8
      - name: Run with Claude-3-5-sonnet-20240620
        run: |
          poetry run python main.py --llm anthropic/claude-3-5-sonnet-20240620
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B8 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # run bot B9
      - name: Run with Claude-3-5-sonnet-20241022
        run: |
          poetry run python main.py --llm anthropic/claude-3-5-sonnet-20241022
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B9 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # run bot B10
      - name: Run with Gemini-exp-1206
        run: |
          poetry run python main.py --llm gemini/gemini-exp-1206 --concurrency 2
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B10 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      # run bot B11
      - name: Run with Grok-beta
        run: |
          poetry run python main.py --llm xai/grok-beta
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B11 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
      # run bot B12
      - name: Run with Meta-Llama-3.1-405B-Instruct-Turbo
        run: |
          poetry run python main.py --llm together_ai/meta-llama/Meta-Llama-3.1-405B-Instruct-Turbo
        env:
          METACULUS_TOKEN: ${{ secrets.METACULUS_TOKEN_B12 }}
          ASKNEWS_CLIENT_ID: ${{ secrets.ASKNEWS_CLIENT_ID }}
          ASKNEWS_SECRET: ${{ secrets.ASKNEWS_SECRET }}
          TOGETHERAI_API_KEY: ${{ secrets.TOGETHERAI_API_KEY }}
